version: '3.1'
services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.2-fpm-alpine
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret